version: '3.8'

services:
  mock-rest-server:
    container_name: mock-rest-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file: ./example/docker.env
    volumes:
      - ./example/MockCalls:/app/MockCalls
      - ./example/Endpoints:/app/Endpoints
