version: '3.8'

services:
  mock-rest-server:
    container_name: mock-rest-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file: docker.env
    volumes:
      - ./MockCalls:/app/MockCalls
      - ./Endpoints:/app/Endpoints
