name: MockRestAPI
run-name: Build and Test
on: [push]
jobs:
  build-and-test-solution:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Install Tools
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
      - name: Install dependencies
        run: dotnet restore ./src/MockRestServer.sln
      - name: Build 
        run: dotnet build ./src/MockRestServer.sln
      - name: Test 
        run: dotnet test ./src/MockRestServer.sln --logger trx --collect:"XPlat Code Coverage"
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: test-results
          path: "**/*.trx"                            
          reporter: dotnet-trx
          fail-on-error: true
      - name: Code Coverage
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.12
        with:
          reports: "**/coverage.cobertura.xml"
          targetdir: TestResults
      - name: Publish code coverage
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: "**/*.html"
      - run: echo "🍏 This job's status is ${{ job.status }}."
      
  create-and-publish-docker-image:
    runs-on: ubuntu-latest
    needs: build-and-test-solution
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: adipa/mock-rest-server:latest